Fix AttributeError when Model inherit a manager
AttributeError: 'NoneType' object has no attribute 'get_query_set'
When a Model inherit from an Abstract one which implement a Manager.
In this case '_default_manager' is defined but equal to None